---
- name: " Play 1: Retrive All VLANs from Arista Switches"
  hosts: leaf
  vars_files: vlan_design.yml
  tasks:
    - name: "Get All VLANs"
      eos_command:
        commands: show vlan | json
      register: show_vlan

    # - debug: var=show_vlan
    
    - name: "Validate VLANs are Present"
      assert:
        that: (item.id | string) in show_vlan.stdout[0].vlans.keys()
        fail_msg: "VLAN:{{ item.id }} is NOT configured "
        success_msg: "VLAN:{{ item.id }} is configured "
      loop: "{{ vlan_data[inventory_hostname] }}"
      delegate_to: localhost
