---
- name: "Play1: Gather Public SSH keys"
  hosts: all
  tags: collect
  tasks:
    - name: Capture SSH Public Keys for Remote Nodes
      command: ssh-keyscan {{ ansible_host }}
      delegate_to: localhost
      register: ssh_keys

    - debug: var=ssh_keys
      delegate_to: localhost

- name: "Play2: Record Keys in Known Hosts file"
  hosts: localhost
  vars:
    #- hosts_file: "~/.ssh/known_hosts"
    - hosts_file: "./temp_ssh.txt"

  tasks:
    - name: create know hosts file
      file:
        path: "{{ hosts_file }}"
        state: file
      changed_when: false

    - name: Populate the known_hosts file
      blockinfile:
        block: |
          {% for host in groups['all'] if  hostvars[host].ssh_keys.stdout != ''  %}
          {{ hostvars[host].ssh_keys.stdout}}
          {% endfor %}
        path: "{{ hosts_file }}"
        create: yes
