---
- name: Ansible Loop over a List
  hosts: cisco
  gather_facts: no
  tasks:
  - name: Loop over SNMP Servers
    debug:
      msg: "Router {{ hostname }} with snmp server {{ item }}"
    loop: "{{ snmp_servers}}"

- name: Ansible Loop over a Dictionary
  hosts: juniper
  gather_facts: no
  tasks:
  - name: Loop over Username and Passowrds
    debug:
      msg: "Router {{ hostname }} with user {{ item.key }} password {{ item.value }}"
    with_dict: "{{ users}}"
